### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by MSKeith** [Azure-Samples/azure-intelligent-edge-patterns#130]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>The UX is a bit confusing, we need more clarity around what sections do what.  When looking at the term location...what is that describing, camera is good, but then part...again what is that describing....etc.  More clarification would be better.

### Any log messages given by the failure
>

### Expected/desired behavior
>clear understanding of the different ux sections.

### OS and Version?
> All

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by initmahesh** [comment]
fixed in latest build
