### ISSUE TITLE
Definition of "Part"

### ISSUE THREAD

**Issue by MSKeith** [Azure-Samples/azure-intelligent-edge-patterns#146]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>In the side menu view the "part" is unclear.  This should be relabeled something like "Model Reference" or "Model Training" etc.

### Any log messages given by the failure
> No

### Expected/desired behavior
>  Unclear on what it is referencing to.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by initmahesh** [comment]
Checkign with team we can add PArt(object) and part identiciafication -> part(object) identification

**Comment by initmahesh** [comment]
need to discuss internally with UX team

**Comment by initmahesh** [comment]
closed review and let us knwo if you like it ..
