### ISSUE TITLE
factory-ai-vision: InferenceModule failing with libGL.so.1: No such file or directory with "deployment.cpu.template.json"

### ISSUE THREAD

**Issue by psakamoori** [Azure-Samples/azure-intelligent-edge-patterns#196]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
After installing all Azure pre-requisites for running factory-ai-vision. Started following (manual deployment steps):
From: https://github.com/Azure-Samples/azure-intelligent-edge-patterns/tree/master/factory-ai-vision
Step 1: "Option 2: Manual installation building a docker container and deploy by Visual Studio Code"
Filled all the fields in :
env-template (FYI: I have to rename this to .env before building the container image in VSCODE)

Step2: Under EdgeSolutions I used "deployment.cpu.template.json" to build and push container image

### Any log messages given by the failure
> InferenceModule failed "backoff"

![logss](https://user-images.githubusercontent.com/2974647/94351317-6dff7d80-000c-11eb-9314-bf417d9469cd.png)

### Expected/desired behavior
> InferenceModule Edge module should start without backoff

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Ubuntu 16.04 
CPU: Intel Core i7

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by goatwu1993** [comment]
Hi @psakamoori,

Thanks for reporting.
I have just tested and I am guessing perhaps wrong deployment file are used?
```bash
deployment.cpu.template.json
```
instead of 
```bash
deployment.template.json
```

Please let us know if you are facing the issue using ```deployment.cpu.template.json```.

```deployment.template.json``` is deprecated and should be removed since cpu/gpu requires different docker image.
We will also add some comment on ```Readme.md``` .

BR,
Peter Wu

**Comment by initmahesh** [comment]
have you validated this from shell.azure.com where the user doe snot build but deploy the prebuilt image?

**Comment by psakamoori** [comment]
@goatwu1993 Issue reported is when using "deployment.cpu.template.json"  (not deployment.template.json)

**Comment by initmahesh** [comment]
resolved in new build
