### ISSUE TITLE
[FactoryAI] Using a local password protected IP camera as source for LVA not working

### ISSUE THREAD

**Issue by michhar** [Azure-Samples/azure-intelligent-edge-patterns#278]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Deploy locally on device using LVA path (not opencv)
2. Navigate to local web app at port 8181
3. Create new project
3. Add a local IP camera that has a username and password set up (here I used an Axis camera) - so the RTSP URL would look like this example format:  `rtsp://myuser:mypassword@123.456.789.10/axis-media/media.amp` (this is not my real one btw :-) )
4. Deploy with this project/model and live IP camera
5. Wait for model to train
6. Check `iotedge logs lvaEdge` on device
7. View that you get Permission denied `401` error and username/password has been stripped from RTSP url (which is probably good, but indicated to me that this seems to be a permission error and somehow my username and password are not being passed appropriately)

### Any log messages given by the failure

Check of IoT Edge logs for LVA module shows:
```
Context: activityId=<some id>
<6> 2021-03-01 21:05:32.396 +00:00 Events: {
  "id": "<some id>",
  "topic": "/subscriptions/<my azure sub>/resourcegroups/<my rg>/providers/microsoft.media/mediaservices/<my ams account>",
  "subject": "/graphInstances/15/sources/rtspSource",
  "eventType": "Microsoft.Media.Graph.Diagnostics.ProtocolError",
  "eventTime": "2021-03-01T21:05:32.387Z",
  "data": {
    "code": "401",
    "target": "rtsp://<my network camera ip>:554/axis-media/media.amp",
    "protocol": "rtsp"
  },
  "dataVersion": "1.0"
};
```

### Expected/desired behavior
In UI, see my resulting identifications in Deployment pane.

### OS and Version?
- UI viewed on macOS Catalina with Safari and Chrome.
- Solution deployed to NVIDIA Xavier AGX Jetson.

### Versions
- IoT Edge 1.1

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

cc @initmahesh @waitingkuo

**Comment by initmahesh** [comment]
try the fix here please and reopen if it still doe snto work , ,
